[project]
name = "call-me-maybe"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0.0",
    "numpy>=1.26.0",
    "llm-sdk",
    "flake8>=7.3.0",
    "mypy>=1.19.1",
]

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = [
    "torch",
    "transformers",
    "huggingface_hub",
]
ignore_missing_imports = true


[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }